name: CI

on:
  push:
    branches: 
      - 'test-ci'
      - 'master'
  pull_request:
    types:
      - opened
    branches: [ "master" ]

jobs:
  Run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
            node-version: '12.x'

      - run: npm install
      - run: npm run build
      - run: npm test
