name: public for dev

on:
  pull_request:
    branches: [ "master" ]
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.MY_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - run: |
          git config --global user.email "dohard@163.COM"
          git config --global user.name "dohard"
          npm version prerelease --preid=alpha -m ":package:	%s"

      - run: npm install

      - run: npm run build

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: dev
          package: ./dist/package.json

      - name: Commit report
        run: |
          git push
          